# Spring Boot application name
spring.application.name=bookmyseat

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bookmyseat?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql@Dikshant
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

