# Local MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/bookmyseat?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql@Dikshant

jwt.secret=change-this-to-a-long-random-secret-key-at-least-32-characters
jwt.expiration=86400000