# Spring Boot application name
spring.application.name=bookmyseat

# default profile for local development
spring.profiles.active=dev

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver